Removing CglData, more parameters for CglRedSplit

diff --git a/Cgl/configure b/Cgl/configure
--- a/Cgl/configure
+++ b/Cgl/configure
@@ -5100,17 +5100,62 @@ fi
 
 
 
+unset ac_cv_file__________libtool
+unset ac_cv_file_______libtool
+unset ac_cv_file____libtool
+
 LIBTOOL=
-if test -r ../libtool; then
+echo "$as_me:$LINENO: checking for ../libtool" >&5
+echo $ECHO_N "checking for ../libtool... $ECHO_C" >&6
+if test "${ac_cv_file____libtool+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "../libtool"; then
+  ac_cv_file____libtool=yes
+else
+  ac_cv_file____libtool=no
+fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_file____libtool" >&5
+echo "${ECHO_T}$ac_cv_file____libtool" >&6
+if test $ac_cv_file____libtool = yes; then
   coin_config_dir=..
-  LIBTOOL='$(SHELL) $(top_builddir)/../libtool'
+               LIBTOOL='$(SHELL) $(top_builddir)/../libtool'
 fi
+
 if test "x$LIBTOOL" = x; then
-  if test -r ../../libtool; then
-    coin_config_dir=../..
-    LIBTOOL='$(SHELL) $(top_builddir)/../../libtool'
-  fi
+  echo "$as_me:$LINENO: checking for ../../libtool" >&5
+echo $ECHO_N "checking for ../../libtool... $ECHO_C" >&6
+if test "${ac_cv_file_______libtool+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "../../libtool"; then
+  ac_cv_file_______libtool=yes
+else
+  ac_cv_file_______libtool=no
 fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_file_______libtool" >&5
+echo "${ECHO_T}$ac_cv_file_______libtool" >&6
+if test $ac_cv_file_______libtool = yes; then
+  coin_config_dir=../..
+                 LIBTOOL='$(SHELL) $(top_builddir)/../../libtool'
+fi
+
+fi
+# if test "x$LIBTOOL" = x; then
+#   AC_CHECK_FILE([../../../libtool],
+#                 [coin_config_dir=../../..
+#                  LIBTOOL='$(SHELL) $(top_builddir)/../../../libtool'])
+# fi
 
 if test "x$LIBTOOL" = x; then
 # AC_MSG_NOTICE([Creating libtool script (calling COIN_PROG_LIBTOOL).])
@@ -5663,7 +5708,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5666 "configure"' > conftest.$ac_ext
+  echo '#line 5711 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6797,7 +6842,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:6800:" \
+echo "$as_me:6845:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7864,11 +7909,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7867: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7912: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7871: \$? = $ac_status" >&5
+   echo "$as_me:7916: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8132,11 +8177,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8135: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8180: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8139: \$? = $ac_status" >&5
+   echo "$as_me:8184: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8236,11 +8281,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8239: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8284: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8243: \$? = $ac_status" >&5
+   echo "$as_me:8288: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10581,7 +10626,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10584 "configure"
+#line 10629 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10681,7 +10726,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10684 "configure"
+#line 10729 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13025,11 +13070,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13028: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13073: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13032: \$? = $ac_status" >&5
+   echo "$as_me:13077: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13129,11 +13174,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13132: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13177: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13136: \$? = $ac_status" >&5
+   echo "$as_me:13181: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14699,11 +14744,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14702: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14747: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14706: \$? = $ac_status" >&5
+   echo "$as_me:14751: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14803,11 +14848,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14806: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14851: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14810: \$? = $ac_status" >&5
+   echo "$as_me:14855: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17010,11 +17055,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17013: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17058: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17017: \$? = $ac_status" >&5
+   echo "$as_me:17062: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17278,11 +17323,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17281: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17326: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17285: \$? = $ac_status" >&5
+   echo "$as_me:17330: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17382,11 +17427,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17385: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17430: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17389: \$? = $ac_status" >&5
+   echo "$as_me:17434: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20096,16 +20141,6 @@ echo "$as_me: Build is \"$build\"." >&6;}
   esac
 
   case $build in
-    *x86_64-*)
-# Here we need to check if -m32 is specified.  If so, we need to correct sys_lib_search_path_spec
-      if test "$GCC" = yes && (echo $CXXFLAGS $CFLAGS $FFLAGS | $EGREP 'm32' >& /dev/null); then
-        { echo "$as_me:$LINENO: Applying patches to libtool for 32bit compilation" >&5
-echo "$as_me: Applying patches to libtool for 32bit compilation" >&6;}
-        sed -e 's|sys_lib_search_path_spec=".*"|sys_lib_search_path_spec="/lib /usr/lib"|' libtool > conftest.bla
-        mv conftest.bla libtool
-        chmod 755 libtool
-      fi
-      ;;
     *-cygwin* | *-mingw*)
     case "$CXX" in
       cl* | */cl* | CL* | */CL*)
@@ -21763,45 +21798,25 @@ cd $curr_dir
 
 # Finally, we let configure write all the output...
 
-if test x$coin_skip_ac_output != xyes; then
+FADDLIBS="$ADDLIBS"
+if test x"$coin_need_flibs" = xyes; then
+  ADDLIBS="$ADDLIBS $FLIBS"
+fi
 
-  FADDLIBS="$ADDLIBS"
-  if test x"$coin_need_flibs" = xyes; then
-    ADDLIBS="$ADDLIBS $FLIBS"
-  fi
+# library extension
 
-  # library extension
+case "$CC" in
+  cl* | */cl* | CL* | */CL*)
+       LIBEXT=lib ;;
+    *) LIBEXT=a ;;
+esac
 
-  case "$CC" in
-    cl* | */cl* | CL* | */CL*)
-         LIBEXT=lib ;;
-      *) LIBEXT=a ;;
-  esac
+# Define VPATH_DISTCLEANFILES to be everything that needs to be
+# cleaned for distclean in a vpath configuration
 
-  # Define VPATH_DISTCLEANFILES to be everything that needs to be
-  # cleaned for distclean in a vpath configuration
+VPATH_DISTCLEANFILES="$coin_vpath_link_files"
 
-  VPATH_DISTCLEANFILES="$coin_vpath_link_files"
-
-  # Take out subdirectories if their configuration concluded that they
-  # don't need to be compiled
-  if test x"$coin_ac_skip_subdirs" != x; then
-    new_subdirs=
-    for i in $subdirs; do
-      skipme=no
-      for j in $coin_ac_skip_subdirs; do
-        if test $i = $j; then
-          skipme=yes;
-        fi
-      done
-      if test $skipme = no; then
-        new_subdirs="$new_subdirs $i"
-      fi
-    done
-    subdirs="$new_subdirs"
-  fi
-
-  cat >confcache <<\_ACEOF
+cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
 # scripts and configure runs, see configure's option --config-cache.
@@ -23471,20 +23486,20 @@ if test "$no_create" != yes; then
 fi
 
 
-  if test x"$coin_vpath_link_files" = x; then : ; else
-    lnkcmd=
-    if test "$enable_doscompile" = yes; then
-      lnkcmd=cp
-    fi
-    case "$CC" in
-      cl* | */cl* | CL* | */CL*)
-        lnkcmd=cp ;;
-    esac
-    if test "$lnkcmd" = cp; then
-      { echo "$as_me:$LINENO: Copying data files for VPATH configuration" >&5
+if test x"$coin_vpath_link_files" = x; then : ; else
+  lnkcmd=
+  if test "$enable_doscompile" = yes; then
+    lnkcmd=cp
+  fi
+  case "$CC" in
+    cl* | */cl* | CL* | */CL*)
+      lnkcmd=cp ;;
+  esac
+  if test "$lnkcmd" = cp; then
+    { echo "$as_me:$LINENO: Copying data files for VPATH configuration" >&5
 echo "$as_me: Copying data files for VPATH configuration" >&6;}
-    else
-      echo "$as_me:$LINENO: checking whether ln -s works" >&5
+  else
+    echo "$as_me:$LINENO: checking whether ln -s works" >&5
 echo $ECHO_N "checking whether ln -s works... $ECHO_C" >&6
 LN_S=$as_ln_s
 if test "$LN_S" = "ln -s"; then
@@ -23495,12 +23510,12 @@ else
 echo "${ECHO_T}no, using $LN_S" >&6
 fi
 
-      { echo "$as_me:$LINENO: Creating VPATH links for data files" >&5
+    { echo "$as_me:$LINENO: Creating VPATH links for data files" >&5
 echo "$as_me: Creating VPATH links for data files" >&6;}
-      lnkcmd="$LN_S"
-    fi
-    for file in $coin_vpath_link_files; do
-      dir=`(dirname "./$file") 2>/dev/null ||
+    lnkcmd="$LN_S"
+  fi
+  for file in $coin_vpath_link_files; do
+    dir=`(dirname "./$file") 2>/dev/null ||
 $as_expr X"./$file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
 	 X"./$file" : 'X\(//\)[^/]' \| \
 	 X"./$file" : 'X\(//\)$' \| \
@@ -23512,8 +23527,8 @@ echo X"./$file" |
   	  /^X\(\/\/\)$/{ s//\1/; q; }
   	  /^X\(\/\).*/{ s//\1/; q; }
   	  s/.*/./; q'`
-      if test -d $dir; then : ; else
-        { if $as_mkdir_p; then
+    if test -d $dir; then : ; else
+      { if $as_mkdir_p; then
     mkdir -p $dir
   else
     as_dir=$dir
@@ -23538,22 +23553,17 @@ echo X"$as_dir" |
 echo "$as_me: error: cannot create directory $dir" >&2;}
    { (exit 1); exit 1; }; }; }
 
-      fi
-      rm -f $file
-      $lnkcmd $abs_source_dir/$file $file
-    done
-  fi
-
-  if test x$coin_projectdir = xyes; then
-    { echo "$as_me:$LINENO: Configuration of $PACKAGE_NAME successful" >&5
-echo "$as_me: Configuration of $PACKAGE_NAME successful" >&6;}
-  else
-    { echo "$as_me:$LINENO: Main configuration of $PACKAGE_NAME successful" >&5
-echo "$as_me: Main configuration of $PACKAGE_NAME successful" >&6;}
-  fi
-else
-  { echo "$as_me:$LINENO: No configuration of $PACKAGE_NAME necessary" >&5
-echo "$as_me: No configuration of $PACKAGE_NAME necessary" >&6;}
+    fi
+    rm -f $file
+    $lnkcmd $abs_source_dir/$file $file
+  done
 fi
 
+if test x$coin_projectdir = xyes; then
+  { echo "$as_me:$LINENO: Configuration of $PACKAGE_NAME successful" >&5
+echo "$as_me: Configuration of $PACKAGE_NAME successful" >&6;}
+else
+  { echo "$as_me:$LINENO: Main configuration of $PACKAGE_NAME successful" >&5
+echo "$as_me: Main configuration of $PACKAGE_NAME successful" >&6;}
+fi
 
